### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by naoric** [odednavon/my-Guitar-Website#2]
You should 'encode' all HTML entities - even inside tags attribute - for example:
&lt;a href='http://something.com?hello=word&something=else'&gt; &lt;/a&gt;
in this case you should replace the ampersand with the &amp; entity.
Check out these links:
http://www.tutorialspoint.com/html5/html5_entities.htm
http://www.danshort.com/HTMLentities/

**Comment by odednavon** [comment]
Thanks for your comment, Done!
